namespace LtbToSmd.Models;

public enum LTBMeshType
{
    LTB_MESHTYPE_NOTSKINNED = 1,
    LTB_MESHTYPE_EXTRAFLOAT,
    LTB_MESHTYPE_SKINNED,
    LTB_MESHTYPE_SKINNEDALT,
    LTB_MESHTYPE_TWOEXTRAFLOAT
}
